[package]
name = "dns-block"
version = "0.4.3"
authors = ["Ovidiu Ionescu <ovidiu@ionescu.net>"]
edition = "2018"

[dependencies]
fnv = "*"
rayon = "*"
clap= { version = "*", features = ["derive"] }
log="*"
stderrlog="*"
indoc="1.0"
mimalloc = "*"

[profile.release]
lto = true

